### ISSUE TITLE
Add jinja pipeline (config + Makfile.j2)

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/monarch-semantic-similarity-profiles#1]
profiles.yml contains:

```
ontologies:
   - id: upheno2-lattice
   - id: upheno1-equivalent
   - id: upheno1
semantic_similarity_profiles:
   - name: all
      method: semsimian 
      ontology: upheno2-lattice
      branches: 
         subject: UPHENO:0001001
         object: UPHENO:0001001
   - subset: hp-mp
      method: semsimian 
      ontology: upheno2-lattice
      branches: 
         subject: UPHENO:0001001
         object: UPHENO:0001001
      prefixes:
         subject: HP
         object: MP 
   - subset: hp-mp
      method: semsimian 
      ontology: upheno2-lattice
      branches: 
         subject: UPHENO:0001001
         object: UPHENO:0001001
      prefixes:
         subject: HP
         object: MP
   - subset: hp-mp
      method: cosine 
      ontology: upheno2-lattice
      branches: 
         subject: UPHENO:0001001
         object: UPHENO:0001001
      prefixes:
         subject: HP
         object: MP
```

`Makefile.j2` includes all make goals to:

1. generate ontologies in the `ontologies` section of the config.
2. The semantic similarity profiles according to the config

Semsimian is oak semsimian and `cosine` is neat consine similarity - work with Justin and Harry to set this up.
